export const x11Colors = [
  { name: 'alice', hex: '#F0F8FF', web: 'aliceblue' },
  { name: 'antique white', hex: '#faebd7', web: 'antiquewhite' },
  { name: 'aqua', hex: '#00ffff', web: 'aqua' },
  { name: 'aquamarine', hex: '#7fffd4', web: 'aquamarine' },
  { name: 'azure', hex: '#f0ffff', web: 'azure' },
  { name: 'beige', hex: '#f5f5dc', web: 'beige' },
  { name: 'bisque', hex: '#ffe4c4', web: 'bisque' },
  { name: 'black', hex: '#000000', web: 'black' },
  { name: 'blanched almond', hex: '#ffebcd', web: 'blanchedalmond' },
  { name: 'blue', hex: '#0000ff', web: 'blue' },
  { name: 'blue violet', hex: '#8a2be2', web: 'blueviolet' },
  { name: 'brown', hex: '#a52a2a', web: 'brown' },
  { name: 'burlywood', hex: '#deb887', web: 'burlywood' },
  { name: 'cadet blue', hex: '#5f9ea0', web: 'cadetblue' },
  { name: 'chartreuse', hex: '#7fff00', web: 'chartreuse' },
  { name: 'chocolate', hex: '#d2691e', web: 'chocolate' },
  { name: 'coral', hex: '#ff7f50', web: 'coral' },
  { name: 'cornflower blue', hex: '#6495ed', web: 'cornflowerblue' },
  { name: 'cornsilk', hex: '#fff8dc', web: 'cornsilk' },
  { name: 'crimson', hex: '#dc143c', web: 'crimson' },
  { name: 'cyan', hex: '#00ffff', web: 'cyan' },
  { name: 'dark blue', hex: '#00008b', web: 'darkblue' },
  { name: 'dark cyan', hex: '#008b8b', web: 'darkcyan' },
  { name: 'dark goldenrod', hex: '#b8860b', web: 'darkgoldenrod' },
  { name: 'dark gray', hex: '#a9a9a9', web: 'darkgray' },
  { name: 'dark green', hex: '#006400', web: 'darkgreen' },
  { name: 'dark khaki', hex: '#bdb76b', web: 'darkkhaki' },
  { name: 'dark magenta', hex: '#8b008b', web: 'darkmagenta' },
  { name: 'dark olive green', hex: '#556b2f', web: 'darkolivegreen' },
  { name: 'dark orange', hex: '#ff8c00', web: 'darkorange' },
  { name: 'dark orchid', hex: '#9932cc', web: 'darkorchid' },
  { name: 'dark red', hex: '#8b0000', web: 'darkred' },
  { name: 'dark salmon', hex: '#e9967a', web: 'darksalmon' },
  { name: 'dark sea green', hex: '#8fbc8f', web: 'darkseagreen' },
  { name: 'dark slate blue', hex: '#483d8b', web: 'darkslateblue' },
  { name: 'dark slate gray', hex: '#2f4f4f', web: 'darkslategray' },
  { name: 'dark turquoise', hex: '#00ced1', web: 'darkturquoise' },
  { name: 'dark violet', hex: '#9400d3', web: 'darkviolet' },
  { name: 'deep pink', hex: '#ff1493', web: 'deeppink' },
  { name: 'deep sky blue', hex: '#00bfff', web: 'deepskyblue' },
  { name: 'dim gray', hex: '#696969', web: 'dimgray' },
  { name: 'dodger blue', hex: '#1e90ff', web: 'dodgerblue' },
  { name: 'firebrick', hex: '#b22222', web: 'firebrick' },
  { name: 'floral white', hex: '#fffaf0', web: 'floralwhite' },
  { name: 'forest green', hex: '#228b22', web: 'forestgreen' },
  { name: 'fuchsia', hex: '#ff00ff', web: 'fuchsia' },
  { name: 'gainsboro', hex: '#dcdcdc', web: 'gainsboro' },
  { name: 'ghost white', hex: '#f8f8ff', web: 'ghostwhite' },
  { name: 'gold', hex: '#ffd700', web: 'gold' },
  { name: 'goldenrod', hex: '#daa520', web: 'goldenrod' },
  { name: 'gray', hex: '#bebebe', web: 'gray' },
  { name: 'web gray', hex: '#808080', web: 'webgray' },
  { name: 'green', hex: '#00ff00', web: 'green' },
  { name: 'web green', hex: '#008000', web: 'webgreen' },
  { name: 'green yellow', hex: '#adff2f', web: 'greenyellow' },
  { name: 'honeydew', hex: '#f0fff0', web: 'honeydew' },
  { name: 'hot pink', hex: '#ff69b4', web: 'hotpink' },
  { name: 'indian red', hex: '#cd5c5c', web: 'indianred' },
  { name: 'indigo', hex: '#4b0082', web: 'indigo' },
  { name: 'ivory', hex: '#fffff0', web: 'ivory' },
  { name: 'khaki', hex: '#f0e68c', web: 'khaki' },
  { name: 'lavender', hex: '#e6e6fa', web: 'lavender' },
  { name: 'lavender blush', hex: '#fff0f5', web: 'lavenderblush' },
  { name: 'lawn green', hex: '#7cfc00', web: 'lawngreen' },
  { name: 'lemon chiffon', hex: '#fffacd', web: 'lemonchiffon' },
  { name: 'light blue', hex: '#add8e6', web: 'lightblue' },
  { name: 'light coral', hex: '#f08080', web: 'lightcoral' },
  { name: 'light cyan', hex: '#e0ffff', web: 'lightcyan' },
  { name: 'light goldenrod', hex: '#fafad2', web: 'lightgoldenrod' },
  { name: 'light gray', hex: '#d3d3d3', web: 'lightgray' },
  { name: 'light green', hex: '#90ee90', web: 'lightgreen' },
  { name: 'light pink', hex: '#ffb6c1', web: 'lightpink' },
  { name: 'light salmon', hex: '#ffa07a', web: 'lightsalmon' },
  { name: 'light sea green', hex: '#20b2aa', web: 'lightseagreen' },
  { name: 'light sky blue', hex: '#87cefa', web: 'lightskyblue' },
  { name: 'light slate gray', hex: '#778899', web: 'lightslategray' },
  { name: 'light steel blue', hex: '#b0c4de', web: 'lightsteelblue' },
  { name: 'light yellow', hex: '#ffffe0', web: 'lightyellow' },
  { name: 'lime', hex: '#00ff00', web: 'lime' },
  { name: 'lime green', hex: '#32cd32', web: 'limegreen' },
  { name: 'linen', hex: '#faf0e6', web: 'linen' },
  { name: 'magenta', hex: '#ff00ff', web: 'magenta' },
  { name: 'maroon', hex: '#b03060', web: 'maroon' },
  { name: 'web maroon', hex: '#800000', web: 'webmaroon' },
  { name: 'medium aquamarine', hex: '#66cdaa', web: 'mediumaquamarine' },
  { name: 'medium blue', hex: '#0000cd', web: 'mediumblue' },
  { name: 'medium orchid', hex: '#ba55d3', web: 'mediumorchid' },
  { name: 'medium purple', hex: '#9370db', web: 'mediumpurple' },
  { name: 'medium sea green', hex: '#3cb371', web: 'mediumseagreen' },
  { name: 'medium slate blue', hex: '#7b68ee', web: 'mediumslateblue' },
  { name: 'medium spring green', hex: '#00fa9a', web: 'mediumspringgreen' },
  { name: 'medium turquoise', hex: '#48d1cc', web: 'mediumturquoise' },
  { name: 'medium violet red', hex: '#c71585', web: 'mediumvioletred' },
  { name: 'midnight blue', hex: '#191970', web: 'midnightblue' },
  { name: 'mint cream', hex: '#f5fffa', web: 'mintcream' },
  { name: 'misty rose', hex: '#ffe4e1', web: 'mistyrose' },
  { name: 'moccasin', hex: '#ffe4b5', web: 'moccasin' },
  { name: 'navajo white', hex: '#ffdead', web: 'navajowhite' },
  { name: 'navy blue', hex: '#000080', web: 'navyblue' },
  { name: 'old lace', hex: '#fdf5e6', web: 'oldlace' },
  { name: 'olive', hex: '#808000', web: 'olive' },
  { name: 'olive drab', hex: '#6b8e23', web: 'olivedrab' },
  { name: 'orange', hex: '#ffa500', web: 'orange' },
  { name: 'orange red', hex: '#ff4500', web: 'orangered' },
  { name: 'orchid', hex: '#da70d6', web: 'orchid' },
  { name: 'pale goldenrod', hex: '#eee8aa', web: 'palegoldenrod' },
  { name: 'pale green', hex: '#98fb98', web: 'palegreen' },
  { name: 'pale turquoise', hex: '#afeeee', web: 'paleturquoise' },
  { name: 'pale violet red', hex: '#db7093', web: 'palevioletred' },
  { name: 'papaya whip', hex: '#ffefd5', web: 'papayawhip' },
  { name: 'peach puff', hex: '#ffdab9', web: 'peachpuff' },
  { name: 'peru', hex: '#cd853f', web: 'peru' },
  { name: 'pink', hex: '#ffc0cb', web: 'pink' },
  { name: 'plum', hex: '#dda0dd', web: 'plum' },
  { name: 'powder blue', hex: '#b0e0e6', web: 'powderblue' },
  { name: 'purple', hex: '#a020f0', web: 'purple' },
  { name: 'web purple', hex: '#800080', web: 'webpurple' },
  { name: 'rebecca purple', hex: '#663399', web: 'rebeccapurple' },
  { name: 'red', hex: '#ff0000', web: 'red' },
  { name: 'rosy brown', hex: '#bc8f8f', web: 'rosybrown' },
  { name: 'royal blue', hex: '#4169e1', web: 'royalblue' },
  { name: 'saddle brown', hex: '#8b4513', web: 'saddlebrown' },
  { name: 'salmon', hex: '#fa8072', web: 'salmon' },
  { name: 'sandy brown', hex: '#f4a460', web: 'sandybrown' },
  { name: 'sea green', hex: '#2e8b57', web: 'seagreen' },
  { name: 'seashell', hex: '#fff5ee', web: 'seashell' },
  { name: 'sienna', hex: '#a0522d', web: 'sienna' },
  { name: 'silver', hex: '#c0c0c0', web: 'silver' },
  { name: 'sky blue', hex: '#87ceeb', web: 'skyblue' },
  { name: 'slate blue', hex: '#6a5acd', web: 'slateblue' },
  { name: 'slate gray', hex: '#708090', web: 'slategray' },
  { name: 'snow', hex: '#fffafa', web: 'snow' },
  { name: 'spring green', hex: '#00ff7f', web: 'springgreen' },
  { name: 'steel blue', hex: '#4682b4', web: 'steelblue' },
  { name: 'tan', hex: '#d2b48c', web: 'tan' },
  { name: 'teal', hex: '#008080', web: 'teal' },
  { name: 'thistle', hex: '#d8bfd8', web: 'thistle' },
  { name: 'tomato', hex: '#ff6347', web: 'tomato' },
  { name: 'turquoise', hex: '#40e0d0', web: 'turquoise' },
  { name: 'violet', hex: '#ee82ee', web: 'violet' },
  { name: 'wheat', hex: '#f5deb3', web: 'wheat' },
  { name: 'white', hex: '#ffffff', web: 'white' },
  { name: 'white smoke', hex: '#f5f5f5', web: 'whitesmoke' },
  { name: 'yellow', hex: '#ffff00', web: 'yellow' },
  { name: 'yellow green', hex: '#9acd32', web: 'yellowgreen' },
];
